### ISSUE TITLE
Heavy performance issues

### ISSUE THREAD

**Issue by Corben78** [brian91292/BeatSaber-EnhancedTwitchChat#10]
When starting today Beat Saber 0.12.2 I realized a heavy frame drop, from formerly ~90 fps down to below 20 fps or lower then playing a level.
When starting the game, I can see the fps dropping to 45 already before leaving the intro screen. When clicking continue and the menu shows up, I have already heavy stuttering.

It seems related to the EnhancedTwitchChat plugin, as when I disabled it, the fps are back to normal.

I installed this mod freshly today with the BeatSaberMod installer, so it's including the AsyncTwitchChat and CustomUI mods too.

Any idea, what this could be?

**Comment by brian91292** [comment]
I'm aware of some performance issues in the current version of the mod, and have been working on resolving them. It's been mainly related to animated emotes, though, so not sure if this applies to your problem.

If you could provide some more information about what's going on in chat when it happens, that would be great.

**Comment by Corben78** [comment]
Sorry for replying just now, couldn't test around due to being sick the last 7 days.

I've tested around with different settings, drivers, Steam VR beta, your latest dev build, but nothing helped.

I'm not sure if it's related to EnhancedTwitchChat or maybe even to the new dependency BeatSaberCustomUI.dll, but as soon as I disable either BeatSaberCustomUI.dll (which includes that EnhancedTwitchChat doesn't start) or EnhancedTwitchChat.dll the game runs smooth at 90 fps for me.

I'm not even streaming yet, just logged into the chat. No one wrote something so far. I can see as soon as I start the game, that the fps drops from 90 to 45. When I click continue to get past the warning screen, it's dropping more down to below 20 which makes the game unplayable.

Without EnhancedTwitchChat everything runs smooth. I have several other mods installed, they don't affect the fps so far. But I also tried just using EnhancedTwitchChat without any other mod, here the fps are affected.

I couldn't find any log files, how could I provide you with more helpful information?

**Comment by Corben78** [comment]
Okay, I'm sorry again. Looks like it was an issue on my end.
I completely delete my Beat Saber installation, and installed everything from scratch. Now the issue is gone.
Looks like an old config from somewhere was interfering? Can't tell anymore, as when Steam uninstalls the game, it completely deletes all files. I lost my perfect config of the 3rd camera view this way :)

Nevertheless, it seems there was "just" a strange side effect causing this.

**Comment by brian91292** [comment]
Glad you got it resolved.
