### ISSUE TITLE
Just showing the lock

### ISSUE THREAD

**Issue by Corben78** [brian91292/BeatSaber-EnhancedTwitchChat#2]
Thanks for updating the EnhancedTwitchChat plugin for the latest Beat Saber 0.12.0 update. I appreciate this Twitch chat plugin a lot!

As mentioned on the release page, I installed the AsyncTwitch.dll, which I got from https://www.modsaber.org/mod/asynctwitchlib/1.0.2, as on the AsyncTwitch github [release](https://github.com/Soliel/AsyncTwitch/releases) page is no download. I entered the data in `Beat Saber/Config/AsyncTwitchConfig.json` (though I'm not sure about the syntax of the OAuth token, if it needs a `oauth:` prefix or not, I tried both).

The mod seems to work, as I see the lock which disables moving of the chat window but I cannot see the actual chat window. Any idea what that could be?

I already deleted the file `Beat Saber/UserData/EnhancedTwitchChat.ini`which was re-created, which didn't help though.

**Comment by Corben78** [comment]
Awesome, thanks you for your quick answer!
Unfortunately I'm unable to compile it myself, would it be possible to provide the compiled AsyncTwitch.dll you have created to make it work on your side?

**Comment by brian91292** [comment]
I'm talking to the mod author of AsyncTwitch now and if we don't come to a resolution here shortly then yes.

**Comment by brian91292** [comment]
You can use this version of AsyncTwitch for now to get around the issue:
https://cdn.discordapp.com/attachments/454551991914332161/517108847748448266/AsyncTwitch.dll

Also, copy this file to your Beat Saber directory (in the same folder as Beat Saber.exe):
https://cdn.discordapp.com/attachments/454551991914332161/517104954872168448/NLog.dll

**Comment by brian91292** [comment]
Just gonna leave this open so other people can see it if they have the same problem.

**Comment by brian91292** [comment]
For anyone having this issue, use the latest AsyncTwitch (download it at https://www.modsaber.org/mod/asynctwitchlib/), and make sure to add your twitch username and oauth token in the AsyncTwitch config file.

**Comment by Corben78** [comment]
Thank you very much for taking care of this!
