### ISSUE TITLE
Static emotes

### ISSUE THREAD

**Issue by ceriath** [brian91292/BeatSaber-EnhancedTwitchChat#7]
It would be cool to add a setting to turn off animated gif emotes, so they are shown static instead. I think an older version did this automatically when too many emotes got spammed?

**Comment by brian91292** [comment]
I'll add this in the next few days

**Comment by brian91292** [comment]
Also, that was probably a bug causing the emotes to not animate in the old version 😛

**Comment by brian91292** [comment]
This feature is now in the public version of Enhanced Twitch Chat. It has not been approved on the mod installer but you can find a link to it in the releases section here on Github.
