### ISSUE TITLE
enhancedtwitchchat.ini

### ISSUE THREAD

**Issue by Justice124** [brian91292/BeatSaber-EnhancedTwitchChat#8]
"run the game once to generate the EnhancedTwitchChat.ini file in the UserData folder inside your Beat Saber directory." this file never popped up even after i tried to re-download this and run the game.

**Comment by brian91292** [comment]
This only happens if you failed to install asynctwitch or customui. Rerun the mod installer and don't uncheck anything if it auto checks it.

**Comment by Justice124** [comment]
it didnt tell me to download anything, just transfer the files which i did. not sure if i put them in the wrong spot? i put them here C:\Program Files (x86)\Steam\steamapps\common\Beat Saber
but yea i didnt see anything to say hey install this and this.

**Comment by Justice124** [comment]
mission accomplished. idk what i did  wrong but i fixed it
