### ISSUE TITLE
"Failed to join channel" message

### ISSUE THREAD

**Issue by Avigyl** [brian91292/BeatSaber-EnhancedTwitchChat#9]
After multiple reinstalls and setting up following all the provided instructions, I still can't get this mod to work. I also have Async Twitch setup, and it still doesn't help

The attached file is what I see in the game

![failedtojoin](https://user-images.githubusercontent.com/46161213/50445983-36523600-094d-11e9-9876-6d1e5118fe6b.png)

**Comment by brian91292** [comment]
https://i.imgur.com/Rw9SYsq.jpg

Read the instructions in readme.md.

**Comment by Avigyl** [comment]
Is there something I'm missing besides adding my Twitch username in the .ini file?

At this point, I got a feeling like it's not able to connect to Twitch itself rather than my chat

**Comment by Avigyl** [comment]
I might have found the possible issue. 
Port 6667 is blocked by my ISP, meaning IRC can't be used unless a different port is used?

**Comment by brian91292** [comment]
Try the latest version of the plugin, and post another screenshot. It has more verbose error messages when you fail to connect for some reason.
https://www.dropbox.com/s/6qmz8oz0v555wqy/EnhancedTwitchChat.dll?dl=0

**Comment by Avigyl** [comment]
Still failing even after filling in the .ini and .json files with my Twitch username and oauth key
![desktop screenshot 2018 12 27 - 17 35 49 17](https://user-images.githubusercontent.com/46161213/50475020-25adc880-09fe-11e9-8a37-69ef7d27f54d.png)
